object Versions {
    const val kotlinVersion = "1.6.10"
    const val kspVersion = "1.6.10-1.0.4"
    const val gradleVersion = "7.1.3"

    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.6.0"
    const val composeVersion = "1.1.1"
    const val navigationComposeVersion = "2.4.2"
    const val activityComposeVersion = "1.4.0"
    const val lifecycleRuntimeKtxVersion = "2.4.1"
    const val workVersion = "2.7.1"
    const val accompanistSystemUiControllerVersion = "0.24.6-alpha"
    const val hiltVersion = "2.42"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val hiltWorkVersion = "1.0.0"
    const val hiltExtensionCompilerVersion = "1.0.0"
    const val ktorVersion = "2.0.0"
    const val roomVersion = "2.4.2"
    const val datastorePreferencesVersion = "1.0.0"
    const val timberVersion = "5.0.1"
    const val firebaseCrashlyticsVersion = "2.8.1"
    const val googleServicesVersion = "4.3.10"
    const val firebaseBomVersion = "29.3.1"
}