package com.egorshustov.insearch.core.common.exceptions

enum class VkApiError(val code: Int) {
    UNKNOWN_ERROR_OCCURRED(1),
    APPLICATION_IS_DISABLED(2),
    UNKNOWN_METHOD_PASSED(3),
    INCORRECT_SIGNATURE(4),
    USER_AUTHORIZATION_FAILED(5),
    TOO_MANY_REQUESTS_PER_SECOND(6),
    PERMISSION_IS_DENIED(7),
    INVALID_REQUEST(8),
    FLOOD_CONTROL(9),
    INTERNAL_SERVER_ERROR(10),
    APPLICATION_SHOULD_BE_DISABLED_OR_USER_AUTHORIZED(11),
    CAPTCHA_NEEDED(14),
    ACCESS_DENIED(15),
    HTTPS_REQUIRED(16),
    USER_VALIDATION_REQUIRED(17),
    USER_WAS_DELETED_OR_BANNED(18),
    METHOD_WAS_DISABLED(23),
    USER_CONFIRMATION_REQUIRED(24),
    RATE_LIMIT_REACHED(29),
    PARAMETER_WAS_MISSING_OR_INVALID(100)
}